import { StyleSheet } from "react-native";
export const prostyles = StyleSheet.create({
 
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-start",
    flexDirection: "column",
    position: "relative",
    backgroundColor: "#f1f3f2",
  },
  header: {
    width: "87%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    position: "absolute",
    top: "5%",
    zIndex: 10,
  },
  subheader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 20,
  },
  iconholder: {
    alignItems: "center",
    justifyContent: "center",
    height: 45,
    width: 45,
    borderRadius: 50,
    backgroundColor: "#fff",
  },
  Imagecontainer: {
    width: "100%",
    height: "55%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f1f3f2",
  },
  img: {
    width: "90%",
    height: "70%",
    objectFit: "contain",
    position: "relative",
    top: "5%",
  },
  productDetail: {
    borderTopLeftRadius: 20, // Set the top-left border radius to 10
    borderTopRightRadius: 20,
    backgroundColor: "#fff",
    width: "100%",
    height: "45%",
    alignItems: "center",
    gap: 18,
  },
  productnamestatus: {
    width: "87%",
    alignItems: "center",
    justifyContent: "space-between",
    flexDirection: "row",
    paddingTop: 12,
    position: "relative",
    top: 5,
  },
  productname: {
    fontSize: 20,
  },
  status: {
    backgroundColor: "#ef4d4d",
    paddingVertical: 7,
    paddingHorizontal: 10,
    borderRadius: 12,
  },
  statusname: {
    color: "#fff",
    fontSize: 12,
  },
  ratelikereview: {
    width: "87%",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  greyborder: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 25,
    paddingVertical: 5,
    paddingHorizontal: 14,
  },
  rate: {
    fontSize: 18,
    gap: 10,
  },
  liked: {
    fontSize: 18,
  },
  reviews: {
    fontSize: 12,
    color: "grey",
  },
  description: {
    width: "87%",
    fontSize: 13.5,
  },
  bottompart: {
    height: 80,
    width: "100%",
    // backgroundColor: "aliceblue",
    position: "absolute",
    bottom: 0,
    left: 0,
    alignItems: "center",
    justifyContent: "center",
    // flexDirection:'row',
    borderTopWidth: 1.5,
    borderTopColor: "#f1f3f2",
  },
  subbottompart: {
    width: "87%",
    height: "100%",
    alignItems: "center",
    justifyContent: "space-between",
    flexDirection: "row",
  },
  productprices: {
    flexDirection: "column",
    position: "relative",
  },
  diagonaline:{
    position:'absolute',
    top:16,
    left:-1,
    height:2.5,
    width:55,
    borderWidth:.6,
    borderColor:'#fff',
    borderRadius:40,
    backgroundColor:'gray',
    zIndex:1,
    transform: [{ rotate: '-10deg' }],
  },
  productpreprices: {
    color: "gray",
    fontSize: 18,
    position: "relative",
    // textDecorationLine: "line-through",
    top: 5,
  },
  productnewprices: {
    fontSize: 25,
  },
  addcart: {
    flexBasis: "65%",
    backgroundColor: "#19C463",
    height: "70%",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 15,
  },
  addcarttxt: {
    color: "#fff",
    fontSize: 18,
  },
});
